export const COMPANY_CATEGORIES = [
  { value: "ECOMMERCE", label: "Ecommerce" },
  { value: "FINANCE", label: "Finance" },
  { value: "BANKING", label: "Banking" },
  { value: "INSURANCE", label: "Insurance" },
  { value: "EDUCATION", label: "Education" },
  { value: "EDTECH", label: "EdTech" },
  { value: "HEALTHCARE", label: "Healthcare" },
  { value: "HOSPITAL", label: "Hospital" },
  { value: "PHARMACY", label: "Pharmacy" },
  { value: "FOOD_DELIVERY", label: "Food Delivery" },
  { value: "RESTAURANT", label: "Restaurant" },
  { value: "TRAVEL", label: "Travel" },
  { value: "HOTEL", label: "Hotel" },
  { value: "AIRLINE", label: "Airline" },
  { value: "LOGISTICS", label: "Logistics" },
  { value: "SHIPPING", label: "Shipping" },
  { value: "TELECOM", label: "Telecom" },
  { value: "SOFTWARE", label: "Software" },
  { value: "SAAS", label: "SaaS" },
  { value: "IT_SERVICES", label: "IT Services" },
  { value: "CYBERSECURITY", label: "Cybersecurity" },
  { value: "REAL_ESTATE", label: "Real Estate" },
  { value: "AUTOMOBILE", label: "Automobile" },
  { value: "MEDIA", label: "Media" },
  { value: "ENTERTAINMENT", label: "Entertainment" },
  { value: "STREAMING", label: "Streaming" },
  { value: "GAMING", label: "Gaming" },
  { value: "MANUFACTURING", label: "Manufacturing" },
  { value: "RETAIL", label: "Retail" },
  { value: "FITNESS", label: "Fitness" },
  { value: "SPORTS", label: "Sports" },
  { value: "NGO", label: "NGO" },
  { value: "GOVERNMENT", label: "Government" },
  { value: "LEGAL", label: "Legal" },
  { value: "CONSULTING", label: "Consulting" },
  { value: "RECRUITMENT", label: "Recruitment" },
  { value: "MARKETING", label: "Marketing" }
].sort((a, b) => a.label.localeCompare(b.label));

