# Generated by Django 6.0.6 on 2026-06-13 07:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ECOMMERCE', 'Ecommerce'), ('FINANCE', 'Finance'), ('BANKING', 'Banking'), ('INSURANCE', 'Insurance'), ('EDUCATION', 'Education'), ('EDTECH', 'EdTech'), ('HEALTHCARE', 'Healthcare'), ('HOSPITAL', 'Hospital'), ('PHARMACY', 'Pharmacy'), ('FOOD_DELIVERY', 'Food Delivery'), ('RESTAURANT', 'Restaurant'), ('TRAVEL', 'Travel'), ('HOTEL', 'Hotel'), ('AIRLINE', 'Airline'), ('LOGISTICS', 'Logistics'), ('SHIPPING', 'Shipping'), ('TELECOM', 'Telecom'), ('SOFTWARE', 'Software'), ('SAAS', 'SaaS'), ('IT_SERVICES', 'IT Services'), ('CYBERSECURITY', 'Cybersecurity'), ('REAL_ESTATE', 'Real Estate'), ('AUTOMOBILE', 'Automobile'), ('MEDIA', 'Media'), ('ENTERTAINMENT', 'Entertainment'), ('STREAMING', 'Streaming'), ('GAMING', 'Gaming'), ('MANUFACTURING', 'Manufacturing'), ('RETAIL', 'Retail'), ('FITNESS', 'Fitness'), ('SPORTS', 'Sports'), ('NGO', 'NGO'), ('GOVERNMENT', 'Government'), ('LEGAL', 'Legal'), ('CONSULTING', 'Consulting'), ('RECRUITMENT', 'Recruitment'), ('MARKETING', 'Marketing')], max_length=50)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
