# Generated by Django 6.0.6 on 2026-06-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='faiss_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
