# Generated by Django 6.0.6 on 2026-07-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='feedback',
            field=models.CharField(blank=True, choices=[('helpful', 'Helpful'), ('unhelpful', 'Unhelpful')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='feedback_missing_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='topic',
            field=models.CharField(default='General Query', max_length=100),
        ),
    ]
