# Generated by Django 6.0.6 on 2026-07-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='missing_data_summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
